<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-question.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
	Persian Translate By http://www.question2answer-farsi.com
*/

	return array(
		'1_answer_title' => '1 پاسخ',
		'a_convert_to_c_on' => 'تبدیل این پاسخ به یک نظر درباره:',
		'a_convert_to_c' => 'تبدیل این پاسخ به یک نظر',
		'a_convert_warn_cs' => 'هشدار : این تبدیل را نمیتوان معکوس کرد و همچنین باعث جابجایی این پاسخ/ها خواهد شد',
		'a_convert_warn' => 'هشدار: این تبدیل را نمی توان معکوس کرد.',
		'a_notify_email' => 'مرا از طریق ایمیل آگاه کن اگر پاسخ من انتخاب شد یا دارای دیدگاهی بود:',
		'a_notify_label' => 'مرا از طریق ایمیل آگاه کن اگر پاسخ من انتخاب شد یا دارای دیدگاهی بود',
		'a_notify_x_label' => 'مرا از طریق ایمیل آگاه کن (^) اگر پاسخ من بهترین بود یا دیدگاهی فرستاده شد',
		'a_waiting_your_approval' => 'این پاسخ در انتظاره تایید شماست',
		'a_your_waiting_approval' => 'پاسخ شما در کوتاه ترین زمان بررسی و تایید میشود',
		'add_answer_button' => 'افزودن پاسخ',
		'add_comment_button' => 'افزودن دیدگاه',
		'add_q_favorites' => 'افزودن این سوال به علاقه مندی های من',
		'anon_name_label' => 'نام شما برای نمایش - اختیاری ',
		'answer_button' => 'پاسخ',
		'answer_limit' => 'پاسخ های ورودی بیش از اندازه می باشد لطفا ساعتی دیگر تلاش کنید',
		'answer_must_be_approved' => 'حساب کاربری شما باید تایید شود تا بتوانید به سوالی پاسخ دهید',
		'answer_must_confirm' => 'لطفا ^5آدرس ایمیل خود را تایید کنید^6 تا بتوانید سوال بپرسید.',
		'answer_must_login' => 'لطفا ^1وارد شده^2 یا ^3عضو شوید^4 تا بتوانید سوال بپرسید',
		'answer_q_popup' => 'پاسخ به این سوال',
		'approve_button' => 'تایید',
		'ask_button' => 'پرسش سوال',
		'ask_follow_from_a' => 'سوال شما مربوط به این پاسخ:',
		'ask_follow_title' => 'پرسیدن سوال مشابه',
		'ask_limit' => 'تعداد سوالات دریافتی بسیار زیاد است - لطفا لحظاتی دیگر تلاش کنید',
		'ask_must_be_approved' => 'حساب کاربری شما باید تایید شود تا بتوانید سوالی بپرسید.',
		'ask_must_confirm' => 'لطفا ^5آدرس ایمیل خود را تایید کنید^6 تا بتوانید سوال بپرسید.',
		'ask_must_login' => 'لطفا ^1وارد شده^2 یا ^3عضو شوید^4 تا بتوانید سوال بپرسید',
		'ask_same_q' => 'قبل از ارسال سوال اطمینان حاصل کنید که این سوال قبلا منتشر نشده باشد',
		'ask_title' => 'پرسش سوال جدید',
		'c_notify_email' => 'مرا از طریق این آدرس ایمیل آگاه کن اگر دیدگاهی بعد از دیدگاه من منتشر گردید:',
		'c_notify_label' => 'مرا از طریق ایمیل آگاه کن اگر دیدگاهی بعد از دیدگاه من منتشر گردید',
		'c_notify_x_label' => 'مرا از طریق ایمیل آگاه کن (^) اگر دیدگاهی بعد از دیدگاه من منتشر گردید',
		'c_waiting_your_approval' => 'این دیدگاه در انتظار تایید شماست',
		'c_your_waiting_approval' => 'دیدگاه شما در کوتاه ترین زمان بررسی و منتشر میشود',
		'category_js_note' => 'برای انتخاب یک دسته بندی لطفا جاوا اسکریپت مرورگر خود را فعال کنید',
		'category_required' => 'لطفا یک دسته بندی را انتخاب کنید',
		'category_ask_not_allowed' => 'شما اجازه پرسیدن سوال در این دسته بندی را ندارید',
		'claim_button' => 'من این را خواهم نوشت',
		'clear_flags_button' => 'حذف نشانه گذاری ها به عنوان هرزنامه',
		'clear_flags_popup' => 'حذف نشانه گذاری هرزنامه تمام کاربران',
		'close_button' => 'بستن',
		'close_duplicate_error' => 'سوال مشابه یافت نمیشود - لطفا شماره ی سوال را از آدرس آن وارد نمایید',
		'close_duplicate' => 'این سوال مشابه سوال دیگر است',
		'close_form_button' => 'بستن سوال',
		'close_form_title' => 'بستن این سوال',
		'close_original_note' => 'شما همواره میتوانید از طریق آدرس سوال شماره آنرا بدست آورید',
		'close_original_title' => 'آدرس سوال اصلی:',
		'close_q_popup' => 'بستن این سوال برای هر پاسخ جدید',
		'close_reason_title' => 'دلیل شما برای بستن این سوال:',
		'closed_as_duplicate' => 'ببندید به عنوان تکراری از:',
		'closed_with_note' => 'ببندید با توجه به این نکته:',
		'comment_a_popup' => 'افزودن دیدگاه برای این پاسخ',
		'comment_button' => 'دیدگاه',
		'comment_limit' => 'تعداد دیدگاه های دریافتی بیش از اندازه است - لطفا چند لحظه بعد تلاش کنید',
		'comment_must_be_approved' => 'پیش از آنکه دیدگاهی ارسال کنید , حساب کاربری شما باید تایید شود',
		'comment_must_confirm' => 'لطفا ^5آدرس ایمیل خود را تایید کنید^6 تا بتوانید دیدگاهی ارسال کنید',
		'comment_must_login' => 'لطفا ^1وارد شده^2 یا ^3عضو شوید^4 تا بتوانید دیدگاهی ارسال نمایید',
		'comment_on_a' => 'در پاسخ: ',
		'comment_on_q' => 'در سوال: ',
		'comment_q_popup' => 'افزودن دیدگاه برای این سوال',
		'delete_a_popup' => 'حذف این پاسخ برای همیشه',
		'delete_button' => 'حذف',
		'delete_c_popup' => 'حذف این دیدگاه برای همیشه',
		'delete_q_popup' => 'حذف این سوال برای همیشه',
		'duplicate_content' => 'بنظر میرسد درخواست شما تکراری میباشد',
		'edit_a_popup' => 'ویرایش این پاسخ',
		'edit_a_title' => 'ویرایش پاسخ',
		'edit_button' => 'ویرایش',
		'edit_c_popup' => 'ویرایش این دیدگاه',
		'edit_c_title' => 'ویرایش دیدگاه',
		'edit_must_confirm' => 'لطفا ^5ایمیل خود را تایید کنید^6 تا بتوانید این مرد را ویرایش کنید.',
		'edit_must_login' => 'لطفا ^1وارد شده^2 یا ^3عضوشوید^4 تا بتوانید این مورد را ویرایش نمایید.',
		'edit_q_popup' => 'ویرایش این سوال',
		'edit_q_title' => 'ویرایش سوال',
		'example_tags' => 'برچسب های نمونه:',
		'flag_a_popup' => 'نشانه گذاری این پاسخ به عنوان نامناسب یا هرزنامه',
		'flag_button' => 'هرزنامه',
		'flag_c_popup' => 'نشانه گذاری این دیدگاه به عنوان نامناسب یا هرزنامه.',
		'flag_hide_button' => 'نشانه گذاری به عنوان هرزنامه و مخفی سازی',
		'flag_limit' => 'تعداد نشانه گذاری ها بیش از اندازه است - لطفا چند لحظه بعد تلاش کنید',
		'flag_must_confirm' => 'لطفا ^5آدرس ایمیل خود را تایید نمایید^6 تا بتوانید پست ها را به عنوان هرزنامه نشانه گذاری کنید.',
		'flag_must_login' => 'لطفا ^1وارد شده^2 یا ^3عضو شودید^4 تا بتوانید پست ها را به عنوان هرزنامه نشانه گذاری کنید.',
		'flag_not_allowed' => 'نشانه گذاری این مورد به عنوان هرزنامه مجاز نیست',
		'flag_q_popup' => 'نشانه گذاری این سوال به عنوان نامناسب یا هرزنامه',
		'follow_a_popup' => 'یک سوال مشابه با این پاسخ بپرسید',
		'follow_button' => 'پرسیدن سوال مشابه',
		'follows_a' => 'مربوط به این پاسخ:',
		'follows_q' => 'درباره این سوال',
		'hide_a_popup' => 'مخفی سازی این سوال',
		'hide_button' => 'پنهان',
		'hide_c_popup' => 'مخفی سازی این دیدگاه',
		'hide_q_popup' => 'مخفی سازی این سوال',
		'matching_tags' => 'تطابق برچسب:',
		'max_tags_x' => 'بیشترین تعداد برچسب ^ عدد میباشد',
		'min_tags_x' => 'لطفا حداقل ^ برچسب وارد نمایید',
		'notify_email_note' => 'حریم شخصی : آدرس ایمیل شما محفوظ میماند و برای استفاده های تجاری و تبلیغاتی به کار نمی رود',
		'q_category_label' => 'دسته بندی:',
		'q_content_label' => 'متن اصلی سوال:',
		'q_hidden_author' => 'این سوال توسط پرسشگرش مخفی شده است',
		'q_hidden_flagged' => 'این سوال به عنوان هرزنامه نشانه گذاری و مخفی شده است',
		'q_hidden_other' => 'این سوال مخفی شده است',
		'q_notify_email' => 'در صورتی که سوالم دارای پاسخ یا دیدگاهی بود مرا از طریق ایمیل آگاه کن',
		'q_notify_label' => 'در صورتی که سوالم دارای پاسخ یا دیدگاهی بود مرا از طریق ایمیل آگاه کن',
        'q_notify_x_label' => 'در صورتی که سوالم دارای پاسخ یا دیدگاهی بود مرا از طریق ایمیل (^) آگاه کن',
		'q_tags_comma_label' => 'برچسب ها - استفاده از ویرگول (،) یا فاصله برای جداسازی کلمات:',
		'q_tags_label' => 'برچسب ها - استفاده از ویرگول یا فاصله برای جدا سازی',
		'q_title_label' => 'عنوان سوال:',
		'q_waiting_approval' => 'این سوال در انتظار تایید است',
		'q_waiting_your_approval' => 'این سوال در انتظار تایید شماست',
		'q_your_waiting_approval' => 'سوال شما در کوتاه ترین زمان بررسی و منتشر میشود',
		'recat_button' => 'دسته بندی دوباره',
		'recat_popup' => 'تغییر دسته بندی سوالات',
		'recat_q_title' => 'دسته بندی سوالات از نو',
		'reject_button' => 'ردکردن',
		'remove_q_favorites' => 'حذف این سوال از علاقه مندی های من',
		'reopen_button' => 'بازگشایی',
		'reply_button' => 'پاسخ دادن',
		'reply_c_popup' => 'پاسخ به این دیدگاه',
		'reshow_button' => 'نمایش دوباره',
		'retag_button' => 'برچسب گذاری از نو',
		'retag_cat_popup' => 'تغییر دسته بندی یا برچسب های این سوالات',
		'retag_popup' => 'تغییر برچسب های این سوالات',
		'retag_q_title' => 'نشانه گذاری سوال به عنوان هرزنامه',
		'save_silent_label' => 'ذخیره سازی مخفیانه برای مخفی سازی این ویرایش', 
		'select_popup' => 'برای انتخاب به عنوان بهترین پاسخ کلیک کنید',
		'select_text' => 'بهترین پاسخ',
		'show_1_comment' => 'نمایش 1 دیدگاه',
		'show_1_previous_comment' => 'نمایش 1 دیدگاه قبلی',
		'show_x_comments' => 'نمایش ^ دیدگاه ها',
		'show_x_previous_comments' => 'نمایش ^ دیدگاه قبلی',
		'unflag_button' => 'برداشتن نشانه گذاری به عنوان هرزنامه',
		'unflag_popup' => 'حذف نشانه گذاری هرزنامه',
		'unselect_popup' => 'برای حذف موارد انتخابی کلیک کنید',
		'x_answers_title' => '^ پاسخ ',
		'your_answer_title' => 'پاسخ شما',
		'your_comment_a' => 'دیدگاه شما در رابطه با این پاسخ:',
		'your_comment_q' => 'دیدگاه شما برای این سوال:',
		'approve_a_popup' => "تایید این پاسخ",
		'approve_c_popup' => "تایید این دیدگاه",
		'approve_q_popup' => "تایید این سوال",
		'claim_a_popup' => "اختصاص این پاسخ به شما",
		'claim_c_popup' => "اختصاص این دیدگاه به شما",
		'claim_q_popup' => "اختصاص این سوال به شما",
		'reject_a_popup' => "رد این پاسخ",
		'reject_c_popup' => "رد این دیدگاه",
		'reject_q_popup' => "رد این سوال",
		'reopen_q_popup' => "بازگشایی این سوال",
		'reshow_a_popup' => "بازنمایش این پاسخ",
		'reshow_c_popup' => "بازنمایش این دیدگاه",
		'reshow_q_popup' => "بازنمایش این سوال",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
